[project]
name = "todo-app"
version = "0.1.0"
description = "A simple todo app"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = ["fastapi[standard]==0.115.*", "sqlmodel==0.0.*"]

[dependency-groups]
dev = ["ruff==0.8.*"]
