"""autogeneration

Revision ID: ba3d4818a4c3
Revises: e9d6ff603ca1
Create Date: 2024-07-23 19:27:23.703743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3d4818a4c3'
down_revision: Union[str, None] = 'e9d6ff603ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'done')
    # ### end Alembic commands ###
